### ISSUE TITLE
Constructor argument

### ISSUE THREAD

**Issue by pzac** [MGough/sensorhub#3]
Hi, thanks for this, it's nicer than the code sample provided by the manufacturer.

I've noticed that the constructor now requires a positional argument, you might want to update the README's "how to use" paragraph perhaps?

I'm using `hub = SensorHub(None)` but I'm sure there are better ways to handle that.

**Comment by MGough** [comment]
I'm glad someone has found it useful! The manufacturers documentation was pretty painful, hopefully mine at least helps others decipher their cryptic code to make a version that works for them.

Thanks for pointing out the positional argument issue, a very silly mistake on my part there, I'll update it to allow it to be created without any arguments (i.e `hub = Sensorhub()`), update the docs, and will upload a newer version to PyPi hopefully at some point this week.

**Comment by MGough** [comment]
Took me slightly longer than planned to fix that, but it's now available on master, or as version `2.0.1` on Pypi
